### ISSUE TITLE
无法查询出备案

### ISSUE THREAD

**Issue by qianxun0** [Sma11New/ip2domain#1]
查询备案信息api在设置延迟3秒后，获取近20个备案后就无法获取了。API貌似有限制。

**Comment by onMey** [comment]
我也是，我发现是那个接口的问题，直接单线程，然后加个sleep（3），就没问题。

**Comment by sma11new** [comment]
是的，那个接口存在限制，指定单线程加时延就可以，之前在本地改了忘记上传了

**Comment by gougou123-hash** [comment]
单线程怎么设置呀

**Comment by sma11new** [comment]
新版已经发布，默认单线程呦
